name: Print Software Versions

on: 
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  printSoftwareVersions:
    runs-on: windows-latest
    steps:
    - name: Checkout the repository
      uses: actions/checkout@v2

    - name: Print Windows version
      run: |
        systeminfo | findstr /B /C:"OS Name" /C:"OS Version"
        
    - name: Print Java version
      run: java -version

    - name: Install Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14'

    - name: Print ReactJS version
      run: |
        npx create-react-app --version

    - name: Install Firefox
      run: choco install firefox -y

    - name: Print Firefox version
      run: |
        "C:\Program Files\Mozilla Firefox\firefox.exe" --version
