name: Print Software Versions

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  print_versions:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Print MacBook information
        run: |
          echo "MacBook Pro M3 Pro"
          echo "macOS 15 Sequoia"

      - name: Print Firefox version
        run: |
          echo "Firefox version:"
          echo "Firefox 54.0.1"

      - name: Print ReactJS version
        run: |
          echo "ReactJS version:"
          echo "ReactJS v.18"

      - name: Print Linux Ubuntu version (Server 1)
        run: |
          echo "Linux Ubuntu (Server 1) version:"
          echo "Linux Ubuntu 17.4"

      - name: Print ApplicationServer.jar info
        run: |
          echo "ApplicationServer.jar version:"
          echo "Java version 17"

