name: Print Software Versions

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  PrintSoftwareVersions:
    runs-on: ubuntu-latest
    steps:
      # - name: Print MacBook information
      #   run: |
      #     echo "MacBook Pro: Custom Configuration"
      #     uname -a
      #     echo "Machintosh: macOS Custom Version"
      #     sw_vers || echo "macOS version not available"

      - name: Print Firefox version
        run: |
          echo "Firefox version:"
          echo "Firefox 54.0.1"

      - name: Print ReactJS version
        run: |
          echo "ReactJS version:"
          echo "ReactJS v.18"

  PrintDBMSVersions:
    runs-on: ubuntu-latest
    needs: [PrintSoftwareVersions]
    steps:
      - name: Print PostgreSQL version
        run: psql --version
