name: Print Software Versions

on: 
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  printSoftwareVersions:
    runs-on: windows-latest
    steps:
    - name: Checkout the repository
      uses: actions/checkout@v2

    - name: Print Windows version
      run: |
        systeminfo | findstr /B /C:"OS Name" /C:"OS Version"
        
    - name: Print Java version
      run: java -version

    - name: Install Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14'

    - name: Print ReactJS version
      run: |
        npx create-react-app --version

    - name: Install Google Chrome
      run: choco install googlechrome -y

    - name: Print Google Chrome version
      run: |
        & "C:\Program Files\Google\Chrome\Application\chrome.exe" --version

  printDBMSVersion:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout the repository
      uses: actions/checkout@v2

    - name: Print Ubuntu version
      run: lsb_release -a

    - name: Print PostgreSQL version
      run: |
        sudo apt-get update
        sudo apt-get install -y postgresql
        psql --version
